// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5q2CpqhYjJYjmnKEp7zxOq8nABQ1Ld5Y',
    appId: '1:646290728344:web:e5901afdca52c291a0b7ed',
    messagingSenderId: '646290728344',
    projectId: 'edible-2668e',
    authDomain: 'edible-2668e.firebaseapp.com',
    storageBucket: 'edible-2668e.firebasestorage.app',
    measurementId: 'G-ZMK3Z8RQKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNxmooYMtb1l3hq1MAGDj6wxLDlWWjo6Y',
    appId: '1:646290728344:android:25158d4da82ac5ffa0b7ed',
    messagingSenderId: '646290728344',
    projectId: 'edible-2668e',
    storageBucket: 'edible-2668e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2KxA656csVAXlTIjzaIGOLZzsc1AnTkw',
    appId: '1:646290728344:ios:d130a58659ef8333a0b7ed',
    messagingSenderId: '646290728344',
    projectId: 'edible-2668e',
    storageBucket: 'edible-2668e.firebasestorage.app',
    iosBundleId: 'com.mndrs.edible',
  );
}
