import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'release_localization_overrides.dart';
import 'app_language.dart';
import 'extended_localization_overrides.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static final supportedLocales = AppLanguage.supportedLocales;

  static const localizationsDelegates = <LocalizationsDelegate<dynamic>>[
    _AppLocalizationsDelegate(),
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations) ??
      AppLocalizations(const Locale('en'));

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'discover': 'Discover',
      'messages': 'Messages',
      'notifications': 'Notifications',
      'notificationCenterSubtitle': 'Your messages and discovery alerts.',
      'notificationsEmpty': 'You have no notifications yet.',
      'markAllRead': 'Mark all read',
      'notificationLoadFailed': 'Notifications could not be loaded.',
      'messagesEmpty': 'Your conversations will appear here.',
      'startConversation': 'Start a conversation.',
      'messageHint': 'Write a message…',
      'sendMessage': 'Message',
      'viewProfile': 'View profile',
      'blockUser': 'Block user',
      'unblockUser': 'Unblock user',
      'reportUser': 'Report user',
      'reportSent': 'Report submitted. Thank you.',
      'blockConfirm': 'This user will no longer be able to message you.',
      'unblockConfirm': 'You can message this user again.',
      'userBlocked': 'Messaging is disabled because this user is blocked.',
      'profileNotFound': 'Profile not found.',
      'appUser': 'Edible user',
      'noPublicVisits': 'No public visits yet.',
      'travelDays': 'Travel days',
      'actionFailed': 'Something went wrong. Please try again.',
      'planVacationSubtitle': 'Build a personalized trip in a few steps.',
      'firstName': 'First name',
      'lastName': 'Last name',
      'age': 'Age',
      'hometown': 'Where are you from?',
      'gender': 'Gender',
      'female': 'Female',
      'male': 'Male',
      'nonBinary': 'Non-binary',
      'preferNotToSay': 'Prefer not to say',
      'joinEdible': 'Your next discovery starts here.',
      'loginSubtitle': 'Save places, meet travelers and plan better trips.',
      'registerSubtitle': 'Create your profile and start exploring the world.',
      'secureAccount': 'Your account is private and secure.',
      'personalInfo': 'Personal information',
      'searchHint': 'Search country, city or experience',
      'filters': 'Filters',
      'forYou': 'For You',
      'hiddenGems': 'Hidden Gems',
      'hiddenGemsSubtitle':
          'Less-exposed discoveries ranked with novelty, audience size and your interests.',
      'hiddenGemsEmpty':
          'No hidden gems are available yet. Explore more places and check again.',
      'hiddenGemReasonInterest': 'Under-the-radar and matches your interests',
      'hiddenGemReasonLowExposure': 'Still discovered by very few travelers',
      'hiddenGemReasonLocal': 'A less-obvious discovery worth exploring',
      'forYouPersonalizedSubtitle':
          'Ranked from the discovery interests you have shown in Edible.',
      'forYouLearningSubtitle':
          'Edible is still learning your taste. These are safe discovery picks for now.',
      'forYouEmpty': 'Explore a few places and Edible will start learning what you enjoy.',
      'forYouReasonInterest': 'Because this matches your interests',
      'forYouReasonFeatured': 'Featured discovery while we learn your taste',
      'forYouReasonExplore': 'A discovery to broaden your trip',
      'recommendationUseful': 'More like this',
      'recommendationNotForMe': 'Not for me',
      'advancedFilters': 'Advanced filters',
      'clearAll': 'Clear all',
      'filterCountry': 'Country',
      'filterCity': 'City',
      'filterCategory': 'Category',
      'featuredOnly': 'Featured only',
      'featuredOnlySubtitle': 'Show Edible highlights first.',
      'distanceFilter': 'Maximum distance',
      'anyDistance': 'Any distance',
      'sortBy': 'Sort by',
      'sortRecommended': 'Recommended',
      'sortFeatured': 'Featured',
      'sortAZ': 'A–Z',
      'applyFilters': 'Apply filters',
      'distanceNeedsLocation':
          'Turn on location to apply the distance filter.',
      'useMyLocation': 'Use location',
      'places': 'Places',
      'food': 'Food',
      'snacks': 'Snacks',
      'culture': 'Culture',
      'fruit': 'Fruit',
      'drinks': 'Drinks',
      'favorites': 'Favorites',
      'profile': 'Profile',
      'guest': 'Guest',
      'signIn': 'Sign in',
      'signOut': 'Sign out',
      'language': 'Language',
      'favoritesLogin': 'Sign in to save your discoveries.',
      'favoritesEmptyTitle': 'Your favorites are waiting',
      'favoritesEmptyMessage':
          'Save places, foods and cultural discoveries to find them here anytime.',
      'favoritesLoadFailed': 'Favorites could not be loaded',
      'favoritesLoadFailedMessage':
          'Check your connection and try again. Your saved items are still safe.',
      'favoriteUpdateFailed': 'Favorite could not be updated. Please try again.',
      'removeFavorite': 'Remove from favorites',
      'profileGuest': 'You are exploring Edible as a guest.',
      'noResults': 'Nothing found for this filter.',
      'tryAnotherSearch': 'Try another city, country or category.',
      'about': 'About',
      'tags': 'Tags',
      'save': 'Save',
      'saved': 'Saved',
      'exploreMap': 'Explore map',
      'loadError': 'Could not load discoveries.',
      'retry': 'Retry',
      'nearMe': 'Near me',
      'locationError': 'Location could not be accessed.',
      'priceLevel': 'Price level',
      'bestTime': 'Best time',
      'localTip': 'Local tip',
      'openingInfo': 'Opening info',
      'visitDuration': 'Visit duration',
      'vegetarian': 'Vegetarian',
      'vegan': 'Vegan',
      'halal': 'Halal',
      'spicyLevel': 'Spicy level',
      'etiquette': 'Etiquette',
      'do': 'Do',
      'dont': 'Avoid',
      'minutes': 'min',
      'yes': 'Yes',
      'no': 'No',
      'cities': 'Cities',
      'featured': 'Featured',
      'mustTry': 'Must try',
      'cultureGuide': 'Culture guide',
      'discoverCity': 'Discover the city',
      'all': 'All',
      'visited': 'Visited',
      'tried': 'Tried',
      'passport': 'Passport',
      'travelPassport': 'Travel Passport',
      'passportLogin': 'Sign in to build your travel passport.',
      'visitedCountries': 'Visited countries',
      'visitedCities': 'Visited cities',
      'countries': 'Countries',
      'collections': 'Trip collections',
      'newCollection': 'New collection',
      'collectionName': 'Collection name',
      'collectionsLogin': 'Sign in to create trip collections.',
      'collectionsEmpty': 'No trip collections yet.',
      'create': 'Create',
      'items': 'items',
      'addToCollection': 'Add to collection',
      'manageCollections': 'Manage collections',
      'discoveryScore': 'Discovery score',
      'worldDiscovery': 'World discovery',
      'discoveriesCompleted': 'discoveries completed',
      'passportSubtitle': 'Your personal record of places and flavors.',
      'badges': 'Badges',
      'unlocked': 'Unlocked',
      'badgeFirstStep': 'First Step',
      'badgeFirstStepDesc': 'Visit your first discovery.',
      'badgeCityExplorer': 'City Explorer',
      'badgeCityExplorerDesc': 'Visit discoveries in 3 different cities.',
      'badgeWorldExplorer': 'World Explorer',
      'badgeWorldExplorerDesc': 'Visit discoveries in 5 different countries.',
      'badgeFoodExplorer': 'Food Explorer',
      'badgeFoodExplorerDesc': 'Try 10 local foods or drinks.',
      'badgeCultureSeeker': 'Culture Seeker',
      'badgeCultureSeekerDesc': 'Visit 10 cultural discoveries.',
      'badgeGlobalTaster': 'Global Taster',
      'badgeGlobalTasterDesc': 'Try 25 discoveries around the world.',
      'aroundYou': 'Around you',
      'noNearbyDiscoveries': 'No discoveries found in this radius.',
      'checkIn': 'Check in',
      'checkInSuccess': 'Check-in verified. Marked as visited.',
      'checkInTooFar': 'You are too far away to check in. Distance:',
      'clearFilters': 'Clear',
      'noPork': 'No pork',
      'noAlcohol': 'No alcohol',
      'glutenFree': 'Gluten free',
      'foodIntelligence': 'Food intelligence',
      'typicalLocalPrice': 'Typical local price',
      'dietaryInfo': 'Dietary information',
      'containsPork': 'Contains pork',
      'containsAlcohol': 'Contains alcohol',
      'ingredients': 'Ingredients',
      'allergens': 'Allergens',
      'portion': 'Portion',
      'howLocalsEat': 'How locals eat it',
      'whenLocalsEat': 'When locals eat it',
      'beforeYouOrder': 'Before you order',
      'cultureIntelligence': 'Culture intelligence',
      'cultureGuideSubtitle': 'Etiquette, mistakes, safety and useful phrases.',
      'noCultureGuide': 'No culture guide is available for this city yet.',
      'cultureDo': 'Do',
      'cultureDont': 'Don’t',
      'tipping': 'Tipping',
      'transportEtiquette': 'Transport etiquette',
      'religiousEtiquette': 'Religious place etiquette',
      'touristMistakes': 'Common tourist mistakes',
      'safetyTips': 'Safety tips',
      'scamWarnings': 'Common scam warnings',
      'basicPhrases': 'Basic local phrases',
      'offlineCityPacks': 'Offline city packs',
      'offlinePacksEmpty': 'No cities are downloaded yet. Open a city and download its offline pack.',
      'offlineItems': 'offline items',
      'offlinePackDownloaded': 'Available offline',
      'downloadCity': 'Download city',
      'offlinePackSubtitle': 'Save city content, food data and culture guidance to this device.',
      'offlinePackReady': 'City pack is ready for offline use.',
      'tripPlanner': 'Trip planner',
      'tripPlannerSubtitle': 'Build a smart itinerary from Edible discoveries.',
      'planYourDay': 'Plan your day',
      'hours': 'Hours',
      'budget': 'Budget',
      'walking': 'Walking',
      'generatePlan': 'Generate plan',
      'delete': 'Delete',
      'editTrip': 'Edit trip',
      'deleteTrip': 'Delete trip',
      'deleteTripConfirmation':
          'Delete this trip and its saved itinerary? This cannot be undone.',
      'tripUpdated': 'Trip updated.',
      'completeRequiredFields': 'Complete the required fields.',
      'somethingWentWrong': 'Something went wrong.',
      'travelAssistant': 'Travel assistant',
      'assistantHeadline': 'Tell Edible what kind of day you want.',
      'assistantSubtitle': 'Describe your time, budget, food and culture preferences.',
      'assistantHint': 'Example: Rome, 5 hours, cheap food, history, not too much walking.',
      'buildMyRoute': 'Build my route',
      'assistantTips': 'Useful tips',
      'ediblePremium': 'Edible Premium',
      'premiumHeadline': 'Unlock the full Edible travel experience.',
      'premiumSubtitle': 'Offline city packs, advanced planning and the travel assistant are included in Premium.',
      'premiumOffline': 'Download cities for offline use',
      'premiumPlanner': 'Use advanced trip planning',
      'premiumAssistant': 'Use the smart travel assistant',
      'premiumComingSoon': 'Purchases coming soon',
      'restoreSubscription': 'Restore / refresh subscription',
      'premiumPurchaseNote': 'Purchase SDK integration will be added after entitlement testing is complete.',
      'premiumActive': 'Premium active',
      'premiumActiveSubtitle': 'All premium Edible features are unlocked.',
      'premiumActivated': 'Edible Premium is now active.',
      'premiumRestored': 'Your Premium purchase was restored.',
      'noPurchaseFound': 'No active Premium purchase was found.',
      'noOfferings': 'No subscription options are available. Check the RevenueCat offering configuration.',
      'purchaseTermsNote': 'Payment is processed by the App Store or Google Play. Subscription terms and cancellation are managed by your store account.',
      'first24Hours': 'First 24 hours',
      'arrivalGuideSubtitle': 'Airport, transport, SIM, money, safety and first-day essentials.',
      'noArrivalGuide': 'No arrival guide is available for this city yet.',
      'welcomeTo': 'Welcome to',
      'currency': 'Currency',
      'emergency': 'Emergency',
      'airportToCity': 'Airport to city',
      'taxiTips': 'Taxi tips',
      'simEsim': 'SIM / eSIM',
      'firstDayChecklist': 'First-day checklist',
      'arrivalDetectedSubtitle': 'It looks like you have arrived in a new Edible city. Get the essentials before you start exploring.',
      'openFirst24Hours': 'Open First 24 Hours',
      'notNow': 'Not now',
      'automaticPassport': 'Automatic passport',
      'automaticPassportSubtitle': 'Cities detected from your location are added to your travel history automatically.',
      'travelTimeline': 'Travel timeline',
      'travelHistoryEmpty': 'Your automatic travel history will appear here after your first detected arrival.',
      
      'arrivalDetections': 'Location detections',
      'tripMemory': 'Trip memory',
      'openTripMemory': 'Open personal travel journal',
      'myTripTo': 'My trip to',
      'memoryTitle': 'Memory title',
      'memoryNote': 'What do you want to remember?',
      'favoriteFood': 'Favorite food',
      'tripRating': 'How was this trip?',
      'tripMood': 'Trip mood',
      'moodHappy': 'Happy',
      'moodAmazed': 'Amazed',
      'moodRelaxed': 'Relaxed',
      'moodAdventurous': 'Adventurous',
      'tripPhotos': 'Trip photos',
      'addPhoto': 'Add photo',
      'noTripPhotos': 'Add photos to make this memory yours.',
      'saveMemory': 'Save memory',
      'memorySaved': 'Trip memory saved.',
      'memorySaveFailed': 'Trip memory could not be saved.',
      'photoUploadFailed': 'Photo upload failed.',
      'travelVisitNotFound': 'This travel visit could not be found.',
      'shareTripCard': 'Share trip card',
      'sharePassport': 'Share passport',
      'travelCardEditor': 'Travel card editor',
      'editTravelCard': 'Customize travel card',
      'cardFormat': 'Card format',
      'cardTemplate': 'Card template',
      'cardBackground': 'Background photo',
      'templateMinimal': 'Minimal',
      'templatePostcard': 'Postcard',
      'templateBold': 'Bold',
      'noPhoto': 'No photo',
      'shareEditedCard': 'Share this card',
      'myTrips': 'My trips',
      'myTripsSubtitle': 'Plan and manage your saved travel workspaces.',
      'newTrip': 'New trip',
      'createTripWorkspace': 'Create trip workspace',
      'tripWorkspaceSubtitle': 'Keep dates, discoveries and Edible travel tools together.',
      'tripName': 'Trip name',
      'countryCode': 'Country code',
      'country': 'Country',
      'city': 'City',
      'tripNotes': 'Trip notes',
      'savedTripsLogin': 'Sign in to create and sync trips',
      'savedTripsEmpty': 'No saved trips yet. Create your first travel workspace.',
      'savedPlaces': 'saved discoveries',
      'savedTripNotFound': 'This saved trip could not be found.',
      'tripTools': 'Trip tools',
      'tripSavedDiscoveries': 'Saved discoveries',
      'tripSavedDiscoveriesSubtitle': 'Choose the places, foods and experiences you want inside this trip.',
      'days': 'days',
      'dayByDayItinerary': 'Day-by-day itinerary',
      'generateItinerary': 'Generate itinerary',
      'itineraryEmpty': 'Your daily itinerary is empty. Select discoveries in the trip workspace, then generate a plan.',
      'itineraryNeedsDiscoveries': 'Select at least one discovery in this trip before generating the itinerary.',
      'itineraryGenerated': 'Day-by-day itinerary saved.',
      'itineraryGenerateFailed': 'The itinerary could not be generated.',
      'day': 'Day',
      'freeDay': 'Free day — no stops scheduled.',
      'previousDay': 'Previous day',
      'nextDay': 'Next day',
      'min': 'min',
      'remove': 'Remove',
      'optimizeRoute': 'Optimize route',
      'routeMap': 'Route map',
      'walkingRoute': 'Walking route',
      'straightLineFallback':
          'Road route unavailable — showing straight-line preview.',
      'routeUnavailable': 'Route unavailable.',
      'refreshRoute': 'Refresh route',
      'configuredRoutingProvider': 'Configured routing provider',
      'developmentRoutingProvider':
          'Development routing provider — configure production routing before release.',
      'routeReducedFrom': 'Approx. straight-line route reduced from',
      'to': 'to',
    },
    'tr': {
      'discover': 'Keşfet',
      'messages': 'Mesajlar',
      'notifications': 'Bildirimler',
      'notificationCenterSubtitle': 'Mesajların ve keşif bildirimlerin burada.',
      'notificationsEmpty': 'Henüz bildirimin yok.',
      'markAllRead': 'Tümünü okundu yap',
      'notificationLoadFailed': 'Bildirimler yüklenemedi.',
      'messagesEmpty': 'Konuşmaların burada görünecek.',
      'startConversation': 'Bir konuşma başlat.',
      'messageHint': 'Mesaj yaz…',
      'sendMessage': 'Mesaj gönder',
      'viewProfile': 'Profili görüntüle',
      'blockUser': 'Kullanıcıyı engelle',
      'unblockUser': 'Engeli kaldır',
      'reportUser': 'Kullanıcıyı bildir',
      'reportSent': 'Bildirim gönderildi. Teşekkürler.',
      'blockConfirm': 'Bu kullanıcı artık sana mesaj gönderemez.',
      'unblockConfirm': 'Bu kullanıcıya tekrar mesaj gönderebilirsin.',
      'userBlocked': 'Bu kullanıcı engellendiği için mesajlaşma kapalı.',
      'profileNotFound': 'Profil bulunamadı.',
      'appUser': 'Edible kullanıcısı',
      'noPublicVisits': 'Henüz herkese açık ziyaret yok.',
      'travelDays': 'Seyahat günü',
      'actionFailed': 'Bir şeyler ters gitti. Lütfen tekrar dene.',
      'planVacationSubtitle': 'Birkaç adımda kişisel tatil planını oluştur.',
      'firstName': 'Ad',
      'lastName': 'Soyad',
      'age': 'Yaş',
      'hometown': 'Nerelisin?',
      'gender': 'Cinsiyet',
      'female': 'Kadın',
      'male': 'Erkek',
      'nonBinary': 'Non-binary',
      'preferNotToSay': 'Belirtmek istemiyorum',
      'joinEdible': 'Bir sonraki keşfin burada başlıyor.',
      'loginSubtitle': 'Yerleri kaydet, gezginlerle tanış ve seyahatlerini daha iyi planla.',
      'registerSubtitle': 'Profilini oluştur ve dünyayı keşfetmeye başla.',
      'secureAccount': 'Hesabın gizli ve güvenli tutulur.',
      'personalInfo': 'Kişisel bilgiler',
      'searchHint': 'Ülke, şehir veya deneyim ara',
      'filters': 'Filtreler',
      'forYou': 'Senin İçin',
      'hiddenGems': 'Gizli Hazineler',
      'hiddenGemsSubtitle':
          'Daha az keşfedilmiş yerler; yenilik, kitle büyüklüğü ve ilgi alanlarına göre sıralanır.',
      'hiddenGemsEmpty':
          'Henüz uygun bir gizli hazine yok. Biraz daha keşfet ve tekrar kontrol et.',
      'hiddenGemReasonInterest': 'Az biliniyor ve ilgi alanlarınla eşleşiyor',
      'hiddenGemReasonLowExposure': 'Henüz çok az gezgin tarafından keşfedildi',
      'hiddenGemReasonLocal': 'Keşfetmeye değer, daha az belirgin bir seçenek',
      'forYouPersonalizedSubtitle':
          'Edible içindeki gerçek keşif ilgilerine göre sıralandı.',
      'forYouLearningSubtitle':
          'Edible zevkini hâlâ öğreniyor. Şimdilik güvenli keşif önerileri gösteriliyor.',
      'forYouEmpty': 'Birkaç yer keşfet; Edible nelerden hoşlandığını öğrenmeye başlasın.',
      'forYouReasonInterest': 'İlgi alanlarınla eşleştiği için',
      'forYouReasonFeatured': 'Zevkini öğrenirken öne çıkan keşif',
      'forYouReasonExplore': 'Seyahatini çeşitlendirecek bir keşif',
      'recommendationUseful': 'Bunun gibi daha fazla',
      'recommendationNotForMe': 'Bana göre değil',
      'advancedFilters': 'Gelişmiş filtreler',
      'clearAll': 'Tümünü temizle',
      'filterCountry': 'Ülke',
      'filterCity': 'Şehir',
      'filterCategory': 'Kategori',
      'featuredOnly': 'Sadece öne çıkanlar',
      'featuredOnlySubtitle': 'Edible öne çıkanlarını göster.',
      'distanceFilter': 'Maksimum mesafe',
      'anyDistance': 'Mesafe fark etmez',
      'sortBy': 'Sırala',
      'sortRecommended': 'Önerilen',
      'sortFeatured': 'Öne çıkan',
      'sortAZ': 'A–Z',
      'applyFilters': 'Filtreleri uygula',
      'distanceNeedsLocation':
          'Mesafe filtresi için konumunu etkinleştir.',
      'useMyLocation': 'Konumumu kullan',
      'places': 'Yerler',
      'food': 'Yemekler',
      'snacks': 'Atıştırmalıklar',
      'culture': 'Kültür',
      'fruit': 'Meyveler',
      'drinks': 'İçecekler',
      'favorites': 'Favoriler',
      'profile': 'Profil',
      'guest': 'Misafir',
      'signIn': 'Giriş yap',
      'signOut': 'Çıkış yap',
      'language': 'Dil',
      'favoritesLogin': 'Keşiflerini kaydetmek için giriş yap.',
      'favoritesEmptyTitle': 'Favorilerin seni bekliyor',
      'favoritesEmptyMessage':
          'Beğendiğin yerleri, yemekleri ve kültürel keşifleri kaydet; istediğin zaman buradan ulaş.',
      'favoritesLoadFailed': 'Favoriler yüklenemedi',
      'favoritesLoadFailedMessage':
          'Bağlantını kontrol edip tekrar dene. Kayıtlı favorilerin güvende.',
      'favoriteUpdateFailed': 'Favori güncellenemedi. Lütfen tekrar dene.',
      'removeFavorite': 'Favorilerden çıkar',
      'profileGuest': 'Edible uygulamasını misafir olarak keşfediyorsun.',
      'noResults': 'Bu filtre için sonuç bulunamadı.',
      'tryAnotherSearch': 'Başka bir şehir, ülke veya kategori dene.',
      'about': 'Hakkında',
      'tags': 'Etiketler',
      'save': 'Kaydet',
      'saved': 'Kaydedildi',
      'exploreMap': 'Haritada keşfet',
      'loadError': 'Keşif içerikleri yüklenemedi.',
      'retry': 'Tekrar dene',
      'nearMe': 'Yakınımda',
      'locationError': 'Konuma erişilemedi.',
      'priceLevel': 'Fiyat seviyesi',
      'bestTime': 'En iyi zaman',
      'localTip': 'Yerel ipucu',
      'openingInfo': 'Açılış bilgisi',
      'visitDuration': 'Ziyaret süresi',
      'vegetarian': 'Vejetaryen',
      'vegan': 'Vegan',
      'halal': 'Helal',
      'spicyLevel': 'Acılık seviyesi',
      'etiquette': 'Görgü kuralı',
      'do': 'Yap',
      'dont': 'Kaçın',
      'minutes': 'dk',
      'yes': 'Evet',
      'no': 'Hayır',
      'cities': 'Şehirler',
      'featured': 'Öne çıkanlar',
      'mustTry': 'Mutlaka dene',
      'cultureGuide': 'Kültür rehberi',
      'discoverCity': 'Şehri keşfet',
      'all': 'Tümü',
      'visited': 'Ziyaret edildi',
      'tried': 'Denedim',
      'passport': 'Pasaport',
      'travelPassport': 'Seyahat Pasaportu',
      'passportLogin': 'Seyahat pasaportunu oluşturmak için giriş yap.',
      'visitedCountries': 'Ziyaret edilen ülkeler',
      'visitedCities': 'Ziyaret edilen şehirler',
      'countries': 'Ülkeler',
      'collections': 'Gezi koleksiyonları',
      'newCollection': 'Yeni koleksiyon',
      'collectionName': 'Koleksiyon adı',
      'collectionsLogin': 'Gezi koleksiyonları oluşturmak için giriş yap.',
      'collectionsEmpty': 'Henüz gezi koleksiyonu yok.',
      'create': 'Oluştur',
      'items': 'öğe',
      'addToCollection': 'Koleksiyona ekle',
      'manageCollections': 'Koleksiyonları yönet',
      'discoveryScore': 'Keşif skoru',
      'worldDiscovery': 'Dünya keşfi',
      'discoveriesCompleted': 'keşif tamamlandı',
      'passportSubtitle': 'Gezdiğin yerlerin ve denediğin tatların kişisel kaydı.',
      'badges': 'Rozetler',
      'unlocked': 'Kazanıldı',
      'badgeFirstStep': 'İlk Adım',
      'badgeFirstStepDesc': 'İlk keşfini ziyaret et.',
      'badgeCityExplorer': 'Şehir Kaşifi',
      'badgeCityExplorerDesc': '3 farklı şehirde keşif ziyaret et.',
      'badgeWorldExplorer': 'Dünya Kaşifi',
      'badgeWorldExplorerDesc': '5 farklı ülkede keşif ziyaret et.',
      'badgeFoodExplorer': 'Lezzet Kaşifi',
      'badgeFoodExplorerDesc': '10 yerel yemek veya içecek dene.',
      'badgeCultureSeeker': 'Kültür Avcısı',
      'badgeCultureSeekerDesc': '10 kültürel keşfi ziyaret et.',
      'badgeGlobalTaster': 'Dünya Tadımcısı',
      'badgeGlobalTasterDesc': 'Dünyanın farklı yerlerinden 25 keşif dene.',
      'aroundYou': 'Etrafında',
      'noNearbyDiscoveries': 'Bu yarıçapta keşif bulunamadı.',
      'checkIn': 'Konumla doğrula',
      'checkInSuccess': 'Konum doğrulandı. Ziyaret edildi olarak işaretlendi.',
      'checkInTooFar': 'Check-in için çok uzaktasın. Mesafe:',
      'clearFilters': 'Temizle',
      'noPork': 'Domuz ürünü yok',
      'noAlcohol': 'Alkol yok',
      'glutenFree': 'Glütensiz',
      'foodIntelligence': 'Yemek rehberi',
      'typicalLocalPrice': 'Tipik yerel fiyat',
      'dietaryInfo': 'Beslenme bilgileri',
      'containsPork': 'Domuz ürünü içerir',
      'containsAlcohol': 'Alkol içerir',
      'ingredients': 'İçindekiler',
      'allergens': 'Alerjenler',
      'portion': 'Porsiyon',
      'howLocalsEat': 'Yereller nasıl yer?',
      'whenLocalsEat': 'Ne zaman yenir?',
      'beforeYouOrder': 'Sipariş vermeden önce',
      'cultureIntelligence': 'Kültür rehberi',
      'cultureGuideSubtitle': 'Görgü, hatalar, güvenlik ve kullanışlı yerel ifadeler.',
      'noCultureGuide': 'Bu şehir için henüz kültür rehberi yok.',
      'cultureDo': 'Yap',
      'cultureDont': 'Yapma',
      'tipping': 'Bahşiş',
      'transportEtiquette': 'Ulaşım görgüsü',
      'religiousEtiquette': 'Dini mekân görgüsü',
      'touristMistakes': 'Yaygın turist hataları',
      'safetyTips': 'Güvenlik ipuçları',
      'scamWarnings': 'Yaygın dolandırıcılık uyarıları',
      'basicPhrases': 'Temel yerel ifadeler',
      'offlineCityPacks': 'Çevrimdışı şehir paketleri',
      'offlinePacksEmpty': 'Henüz indirilen şehir yok. Bir şehir açıp çevrimdışı paketini indir.',
      'offlineItems': 'çevrimdışı içerik',
      'offlinePackDownloaded': 'Çevrimdışı kullanılabilir',
      'downloadCity': 'Şehri indir',
      'offlinePackSubtitle': 'Şehir içeriklerini, yemek bilgilerini ve kültür rehberini cihaza kaydet.',
      'offlinePackReady': 'Şehir paketi çevrimdışı kullanım için hazır.',
      'tripPlanner': 'Gezi planlayıcı',
      'tripPlannerSubtitle': 'Edible keşiflerinden akıllı bir rota oluştur.',
      'planYourDay': 'Gününü planla',
      'hours': 'Saat',
      'budget': 'Bütçe',
      'walking': 'Yürüyüş',
      'generatePlan': 'Plan oluştur',
      'delete': 'Sil',
      'editTrip': 'Geziyi düzenle',
      'deleteTrip': 'Geziyi sil',
      'deleteTripConfirmation':
          'Bu gezi ve kayıtlı planı silinsin mi? Bu işlem geri alınamaz.',
      'tripUpdated': 'Gezi güncellendi.',
      'completeRequiredFields': 'Zorunlu alanları doldur.',
      'somethingWentWrong': 'Bir şeyler ters gitti.',
      'travelAssistant': 'Seyahat asistanı',
      'assistantHeadline': 'Edible’a nasıl bir gün istediğini anlat.',
      'assistantSubtitle': 'Zamanını, bütçeni, yemek ve kültür tercihlerini yaz.',
      'assistantHint': 'Örnek: Roma, 5 saat, ucuz yemek, tarih, çok yürümek istemiyorum.',
      'buildMyRoute': 'Rotamı oluştur',
      'assistantTips': 'Faydalı ipuçları',
      'ediblePremium': 'Edible Premium',
      'premiumHeadline': 'Edible’ın tüm seyahat deneyiminin kilidini aç.',
      'premiumSubtitle': 'Çevrimdışı şehir paketleri, gelişmiş planlama ve seyahat asistanı Premium’a dahildir.',
      'premiumOffline': 'Şehirleri çevrimdışı kullanım için indir',
      'premiumPlanner': 'Gelişmiş gezi planlayıcıyı kullan',
      'premiumAssistant': 'Akıllı seyahat asistanını kullan',
      'premiumComingSoon': 'Satın alma yakında',
      'restoreSubscription': 'Aboneliği yenile / geri yükle',
      'premiumPurchaseNote': 'Satın alma SDK entegrasyonu entitlement testleri tamamlandıktan sonra eklenecek.',
      'premiumActive': 'Premium aktif',
      'premiumActiveSubtitle': 'Tüm Premium Edible özellikleri açık.',
      'premiumActivated': 'Edible Premium artık aktif.',
      'premiumRestored': 'Premium satın alımın geri yüklendi.',
      'noPurchaseFound': 'Aktif bir Premium satın alım bulunamadı.',
      'noOfferings': 'Abonelik seçeneği bulunamadı. RevenueCat offering yapılandırmasını kontrol et.',
      'purchaseTermsNote': 'Ödeme App Store veya Google Play tarafından işlenir. Abonelik ve iptal işlemleri mağaza hesabından yönetilir.',
      'first24Hours': 'İlk 24 saat',
      'arrivalGuideSubtitle': 'Havalimanı, ulaşım, SIM, para, güvenlik ve ilk gün ihtiyaçları.',
      'noArrivalGuide': 'Bu şehir için henüz varış rehberi yok.',
      'welcomeTo': 'Hoş geldin',
      'currency': 'Para birimi',
      'emergency': 'Acil',
      'airportToCity': 'Havalimanından şehre',
      'taxiTips': 'Taksi ipuçları',
      'simEsim': 'SIM / eSIM',
      'firstDayChecklist': 'İlk gün kontrol listesi',
      'arrivalDetectedSubtitle': 'Yeni bir Edible şehrine gelmiş görünüyorsun. Keşfe başlamadan önce temel bilgileri aç.',
      'openFirst24Hours': 'İlk 24 Saati aç',
      'notNow': 'Şimdi değil',
      'automaticPassport': 'Otomatik pasaport',
      'automaticPassportSubtitle': 'Konumundan algılanan şehirler seyahat geçmişine otomatik eklenir.',
      'travelTimeline': 'Seyahat zaman çizelgesi',
      'travelHistoryEmpty': 'İlk şehir varışın algılandıktan sonra seyahat geçmişin burada görünecek.',
      'arrivalDetections': 'Konum algılamaları',
      'tripMemory': 'Seyahat anısı',
      'openTripMemory': 'Kişisel seyahat günlüğünü aç',
      'myTripTo': 'Seyahatim:',
      'memoryTitle': 'Anı başlığı',
      'memoryNote': 'Bu seyahatten neyi hatırlamak istiyorsun?',
      'favoriteFood': 'Favori yemek',
      'tripRating': 'Bu seyahat nasıldı?',
      'tripMood': 'Seyahat ruh hali',
      'moodHappy': 'Mutlu',
      'moodAmazed': 'Hayran kaldım',
      'moodRelaxed': 'Rahat',
      'moodAdventurous': 'Maceracı',
      'tripPhotos': 'Seyahat fotoğrafları',
      'addPhoto': 'Fotoğraf ekle',
      'noTripPhotos': 'Bu anıyı kişiselleştirmek için fotoğraf ekle.',
      'saveMemory': 'Anıyı kaydet',
      'memorySaved': 'Seyahat anısı kaydedildi.',
      'memorySaveFailed': 'Seyahat anısı kaydedilemedi.',
      'photoUploadFailed': 'Fotoğraf yüklenemedi.',
      'travelVisitNotFound': 'Bu seyahat ziyareti bulunamadı.',
      'shareTripCard': 'Seyahat kartını paylaş',
      'sharePassport': 'Pasaportu paylaş',
      'travelCardEditor': 'Seyahat kartı editörü',
      'editTravelCard': 'Seyahat kartını özelleştir',
      'cardFormat': 'Kart formatı',
      'cardTemplate': 'Kart şablonu',
      'cardBackground': 'Arka plan fotoğrafı',
      'templateMinimal': 'Minimal',
      'templatePostcard': 'Kartpostal',
      'templateBold': 'Cesur',
      'noPhoto': 'Fotoğraf yok',
      'shareEditedCard': 'Bu kartı paylaş',
      'myTrips': 'Seyahatlerim',
      'myTripsSubtitle': 'Kaydedilmiş seyahat çalışma alanlarını planla ve yönet.',
      'newTrip': 'Yeni seyahat',
      'createTripWorkspace': 'Seyahat çalışma alanı oluştur',
      'tripWorkspaceSubtitle': 'Tarihleri, keşifleri ve Edible seyahat araçlarını tek yerde tut.',
      'tripName': 'Seyahat adı',
      'countryCode': 'Ülke kodu',
      'country': 'Ülke',
      'city': 'Şehir',
      'tripNotes': 'Seyahat notları',
      'savedTripsLogin': 'Seyahat oluşturmak ve senkronize etmek için giriş yap',
      'savedTripsEmpty': 'Henüz kayıtlı seyahat yok. İlk seyahat alanını oluştur.',
      'savedPlaces': 'kayıtlı keşif',
      'savedTripNotFound': 'Bu kayıtlı seyahat bulunamadı.',
      'tripTools': 'Seyahat araçları',
      'tripSavedDiscoveries': 'Kaydedilmiş keşifler',
      'tripSavedDiscoveriesSubtitle': 'Bu seyahatte görmek istediğin yerleri, yemekleri ve deneyimleri seç.',
      'days': 'gün',
      'dayByDayItinerary': 'Gün gün seyahat planı',
      'generateItinerary': 'Program oluştur',
      'itineraryEmpty': 'Günlük programın boş. Seyahat alanında keşifleri seç ve ardından program oluştur.',
      'itineraryNeedsDiscoveries': 'Program oluşturmadan önce bu seyahate en az bir keşif ekle.',
      'itineraryGenerated': 'Gün gün seyahat programı kaydedildi.',
      'itineraryGenerateFailed': 'Seyahat programı oluşturulamadı.',
      'day': 'Gün',
      'freeDay': 'Serbest gün — planlanmış durak yok.',
      'previousDay': 'Önceki gün',
      'nextDay': 'Sonraki gün',
      'min': 'dk',
      'remove': 'Kaldır',
      'optimizeRoute': 'Rotayı optimize et',
      'routeMap': 'Rota haritası',
      'walkingRoute': 'Yürüyüş rotası',
      'straightLineFallback':
          'Yol rotası alınamadı — kuş uçuşu önizleme gösteriliyor.',
      'routeUnavailable': 'Rota alınamadı.',
      'refreshRoute': 'Rotayı yenile',
      'configuredRoutingProvider': 'Yapılandırılmış rota sağlayıcısı',
      'developmentRoutingProvider':
          'Geliştirme rota sağlayıcısı — yayın öncesi production routing yapılandır.',
      'routeReducedFrom': 'Yaklaşık kuş uçuşu rota',
      'to': '→',
    },
  };

  String text(String key) {
    final languageCode = locale.languageCode;
    final language = _values[languageCode];
    final extended = extendedLocalizationOverrides[languageCode];
    final overrides = releaseLocalizationOverrides[languageCode];
    final englishOverrides = releaseLocalizationOverrides['en'];

    return extended?[key] ??
        overrides?[key] ??
        language?[key] ??
        englishOverrides?[key] ??
        _values['en']?[key] ??
        key;
  }

  static bool hasTranslation({
    required String languageCode,
    required String key,
  }) {
    return extendedLocalizationOverrides[languageCode]?.containsKey(key) == true ||
        releaseLocalizationOverrides[languageCode]?.containsKey(key) == true ||
        _values[languageCode]?.containsKey(key) == true;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales
      .any((supported) => supported.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
