/// Locale-complete UI overrides for high-visibility navigation and Explore text.
///
/// These keys intentionally live outside the legacy release dictionary so the
/// newly supported locales never fall through to a Turkish/English literal.
const extendedLocalizationOverrides = <String, Map<String, String>>{
  'en': {
    'community': 'Community',
    'showOnMap': 'Show on map',
    'showCity': 'Show city',
    'openDetails': 'Open details',
    'mapEmpty': 'No discoveries found in this city.',
    'mapHint': 'Tap a point on the map to open its details, description and image.',
    'discoveryCount': '{count} discoveries',
    'favoriteAdd': 'Add to favorites',
    'favoriteRemove': 'Remove from favorites',
    'markVisitedBeforeRating': 'Mark this place as visited before rating.',
    'all': 'All',
    'allFilters': 'All',
    'minimumRating': 'Minimum rating',
    'clearFilters': 'Clear filters',
    'exploreTours': 'Explore tours',
    'bookingComingSoon': 'Booking feature coming soon!',
    'cancel': 'Cancel',
    'profileNotFound': 'Profile not found.',
    'countryCode': 'Country code',
    'visitDay': 'Visit day',
    'operationFailed': 'Operation failed',
    'deleteShareTitle': 'Delete this post?',
    'deleteShareMessage': 'This post and all its images will be deleted.',
    'share': 'Share',
    'delete': 'Delete',
    'shareDeleted': 'Post deleted.',
    'shareDeleteFailed': 'Post could not be deleted: {error}',
    'createShare': 'Create post',
    'deleteShare': 'Delete post',
    'viewProfile': 'View profile',
    'filter': 'Filter',
    'noToursFound': 'No tours found',
    'adjustFilters': 'Try adjusting your filters',
    'reset': 'Reset',
    'dailyItinerary': 'Daily itinerary',
    'tourDayLabel': 'Day {day}',
    'visitsLabel': 'Visits',
    'noShareableVisits': 'No shareable visits yet.',
    'atLeastOneImage': 'Select at least one image.',
    'newShare': 'New post',
    'shareFailed': 'Post could not be created: {error}',
    'reviews': 'reviews',
    'loadingImage': 'Loading image…',
    'communityPostHint': 'Add up to 5 photos, a description and a location.',
    'communityCaptionHint': 'Tell people what you discovered…',
    'communityLocationHint': 'e.g. Kayseri, Türkiye',
    'refresh': 'Refresh',
    'shareError': 'Sharing failed: {error}',
  },
  'tr': {
    'community': 'Topluluk',
    'showOnMap': 'Haritada göster',
    'showCity': 'Şehri göster',
    'openDetails': 'Detayları aç',
    'mapEmpty': 'Bu şehirde keşif noktası bulunamadı.',
    'mapHint': 'Bilgilerini, açıklamasını ve görselini açmak için haritadaki bir noktaya dokun.',
    'discoveryCount': '{count} keşif noktası',
    'favoriteAdd': 'Favoriye ekle',
    'favoriteRemove': 'Favoriden çıkar',
    'markVisitedBeforeRating': 'Puan vermeden önce bu yeri ziyaret edildi olarak işaretle.',
    'all': 'Tümü',
    'allFilters': 'Tümü',
    'minimumRating': 'Minimum puan',
    'clearFilters': 'Filtreleri temizle',
    'exploreTours': 'Turları keşfet',
    'bookingComingSoon': 'Rezervasyon özelliği yakında!',
    'cancel': 'Vazgeç',
    'profileNotFound': 'Profil bulunamadı.',
    'countryCode': 'Ülke kodu',
    'visitDay': 'Ziyaret günü',
    'operationFailed': 'İşlem başarısız',
    'deleteShareTitle': 'Paylaşım silinsin mi?',
    'deleteShareMessage': 'Bu paylaşım ve içindeki tüm görseller silinecek.',
    'share': 'Paylaş',
    'delete': 'Sil',
    'shareDeleted': 'Paylaşım silindi.',
    'shareDeleteFailed': 'Paylaşım silinemedi: {error}',
    'createShare': 'Paylaşım oluştur',
    'deleteShare': 'Paylaşımı sil',
    'viewProfile': 'Profili gör',
    'filter': 'Filtrele',
    'noToursFound': 'Tur bulunamadı',
    'adjustFilters': 'Filtrelerini değiştirmeyi dene',
    'reset': 'Sıfırla',
    'dailyItinerary': 'Günlük program',
    'tourDayLabel': '{day}. gün',
    'visitsLabel': 'Ziyaretleri',
    'noShareableVisits': 'Henüz paylaşılabilir bir ziyaret kaydı yok.',
    'atLeastOneImage': 'En az 1 görsel seçmelisin.',
    'newShare': 'Yeni paylaşım',
    'shareFailed': 'Paylaşım oluşturulamadı: {error}',
    'reviews': 'yorum',
    'loadingImage': 'Görsel yükleniyor…',
    'communityPostHint': 'En fazla 5 fotoğraf, açıklama ve konum ekleyebilirsin.',
    'communityCaptionHint': 'Nerede ne keşfettiğini anlat…',
    'communityLocationHint': 'Örn. Kayseri, Türkiye',
    'refresh': 'Yenile',
    'shareError': 'Paylaşım başarısız: {error}',
  },
  'de': {
    'community': 'Community', 'showOnMap': 'Auf Karte anzeigen', 'showCity': 'Stadt anzeigen',
    'openDetails': 'Details öffnen', 'mapEmpty': 'Keine Entdeckungen in dieser Stadt gefunden.',
    'mapHint': 'Tippe auf einen Punkt auf der Karte, um Details, Beschreibung und Bild zu öffnen.',
    'discoveryCount': '{count} Entdeckungen', 'favoriteAdd': 'Zu Favoriten hinzufügen',
    'favoriteRemove': 'Aus Favoriten entfernen', 'markVisitedBeforeRating': 'Markiere den Ort als besucht, bevor du ihn bewertest.',
    'all': 'Alle', 'allFilters': 'Alle', 'minimumRating': 'Mindestbewertung', 'clearFilters': 'Filter löschen',
    'exploreTours': 'Touren entdecken', 'bookingComingSoon': 'Buchungsfunktion kommt bald!', 'cancel': 'Abbrechen',
    'profileNotFound': 'Profil nicht gefunden.', 'countryCode': 'Ländercode', 'visitDay': 'Besuchstag',
    'operationFailed': 'Vorgang fehlgeschlagen', 'deleteShareTitle': 'Beitrag löschen?',
    'deleteShareMessage': 'Dieser Beitrag und alle darin enthaltenen Bilder werden gelöscht.', 'share': 'Teilen',
    'delete': 'Löschen', 'shareDeleted': 'Beitrag gelöscht.', 'shareDeleteFailed': 'Beitrag konnte nicht gelöscht werden: {error}',
    'createShare': 'Beitrag erstellen', 'deleteShare': 'Beitrag löschen', 'viewProfile': 'Profil ansehen',
    'filter': 'Filtern',
    'noToursFound': 'Keine Touren gefunden',
    'adjustFilters': 'Passe deine Filter an',
    'reset': 'Zurücksetzen',
    'dailyItinerary': 'Tagesplan',
    'tourDayLabel': 'Tag {day}',
    'visitsLabel': 'Besuche',
    'noShareableVisits': 'Noch keine teilbaren Besuche vorhanden.',
    'atLeastOneImage': 'Wähle mindestens ein Bild aus.',
    'newShare': 'Neuer Beitrag',
    'shareFailed': 'Beitrag konnte nicht erstellt werden: {error}',
    'reviews': 'Bewertungen',
    'loadingImage': 'Bild wird geladen…',
    'communityPostHint': 'Füge bis zu 5 Fotos, eine Beschreibung und einen Ort hinzu.',
    'communityCaptionHint': 'Erzähle, was du entdeckt hast…',
    'communityLocationHint': 'z. B. Kayseri, Türkiye',
    'refresh': 'Aktualisieren',
    'shareError': 'Teilen fehlgeschlagen: {error}',
  },
  'fr': {
    'community': 'Communauté', 'showOnMap': 'Afficher sur la carte', 'showCity': 'Afficher la ville',
    'openDetails': 'Ouvrir les détails', 'mapEmpty': 'Aucune découverte trouvée dans cette ville.',
    'mapHint': 'Touchez un point sur la carte pour ouvrir ses détails, sa description et son image.',
    'discoveryCount': '{count} découvertes', 'favoriteAdd': 'Ajouter aux favoris', 'favoriteRemove': 'Retirer des favoris',
    'markVisitedBeforeRating': 'Marquez ce lieu comme visité avant de le noter.', 'all': 'Tout', 'allFilters': 'Tout',
    'minimumRating': 'Note minimale', 'clearFilters': 'Effacer les filtres', 'exploreTours': 'Découvrir les visites',
    'bookingComingSoon': 'La réservation sera bientôt disponible !', 'cancel': 'Annuler', 'profileNotFound': 'Profil introuvable.',
    'countryCode': 'Code pays', 'visitDay': 'Jour de visite', 'operationFailed': 'Échec de l’opération',
    'deleteShareTitle': 'Supprimer cette publication ?', 'deleteShareMessage': 'Cette publication et toutes ses images seront supprimées.',
    'share': 'Partager', 'delete': 'Supprimer', 'shareDeleted': 'Publication supprimée.',
    'shareDeleteFailed': 'Impossible de supprimer la publication : {error}', 'createShare': 'Créer une publication',
    'deleteShare': 'Supprimer la publication', 'viewProfile': 'Voir le profil',
    'filter': 'Filtrer',
    'noToursFound': 'Aucune visite trouvée',
    'adjustFilters': 'Essayez de modifier vos filtres',
    'reset': 'Réinitialiser',
    'dailyItinerary': 'Itinéraire quotidien',
    'tourDayLabel': 'Jour {day}',
    'visitsLabel': 'Visites',
    'noShareableVisits': 'Aucune visite partageable pour le moment.',
    'atLeastOneImage': 'Sélectionnez au moins une image.',
    'newShare': 'Nouvelle publication',
    'shareFailed': 'Impossible de créer la publication : {error}',
    'reviews': 'avis',
    'loadingImage': 'Chargement de l’image…',
    'communityPostHint': 'Ajoutez jusqu’à 5 photos, une description et un lieu.',
    'communityCaptionHint': 'Racontez ce que vous avez découvert…',
    'communityLocationHint': 'ex. Kayseri, Türkiye',
    'refresh': 'Actualiser',
    'shareError': 'Échec du partage : {error}',
  },
  'es': {
    'community': 'Comunidad', 'showOnMap': 'Mostrar en el mapa', 'showCity': 'Mostrar ciudad', 'openDetails': 'Abrir detalles',
    'mapEmpty': 'No se encontraron descubrimientos en esta ciudad.', 'mapHint': 'Toca un punto del mapa para abrir sus detalles, descripción e imagen.',
    'discoveryCount': '{count} descubrimientos', 'favoriteAdd': 'Añadir a favoritos', 'favoriteRemove': 'Quitar de favoritos',
    'markVisitedBeforeRating': 'Marca este lugar como visitado antes de valorarlo.', 'all': 'Todo', 'allFilters': 'Todo',
    'minimumRating': 'Valoración mínima', 'clearFilters': 'Borrar filtros', 'exploreTours': 'Explorar tours',
    'bookingComingSoon': '¡La función de reserva estará disponible pronto!', 'cancel': 'Cancelar', 'profileNotFound': 'Perfil no encontrado.',
    'countryCode': 'Código de país', 'visitDay': 'Día de visita', 'operationFailed': 'Operación fallida',
    'deleteShareTitle': '¿Eliminar esta publicación?', 'deleteShareMessage': 'Se eliminarán esta publicación y todas sus imágenes.',
    'share': 'Compartir', 'delete': 'Eliminar', 'shareDeleted': 'Publicación eliminada.',
    'shareDeleteFailed': 'No se pudo eliminar la publicación: {error}', 'createShare': 'Crear publicación',
    'deleteShare': 'Eliminar publicación', 'viewProfile': 'Ver perfil',
    'filter': 'Filtrar',
    'noToursFound': 'No se encontraron tours',
    'adjustFilters': 'Prueba a cambiar los filtros',
    'reset': 'Restablecer',
    'dailyItinerary': 'Itinerario diario',
    'tourDayLabel': 'Día {day}',
    'visitsLabel': 'Visitas',
    'noShareableVisits': 'Aún no hay visitas para compartir.',
    'atLeastOneImage': 'Selecciona al menos una imagen.',
    'newShare': 'Nueva publicación',
    'shareFailed': 'No se pudo crear la publicación: {error}',
    'reviews': 'reseñas',
    'loadingImage': 'Cargando imagen…',
    'communityPostHint': 'Añade hasta 5 fotos, una descripción y una ubicación.',
    'communityCaptionHint': 'Cuenta qué has descubierto…',
    'communityLocationHint': 'p. ej., Kayseri, Türkiye',
    'refresh': 'Actualizar',
    'shareError': 'Error al compartir: {error}',
  },
  'it': {
    'community': 'Community', 'showOnMap': 'Mostra sulla mappa', 'showCity': 'Mostra città', 'openDetails': 'Apri dettagli',
    'mapEmpty': 'Nessuna scoperta trovata in questa città.', 'mapHint': 'Tocca un punto sulla mappa per aprire dettagli, descrizione e immagine.',
    'discoveryCount': '{count} scoperte', 'favoriteAdd': 'Aggiungi ai preferiti', 'favoriteRemove': 'Rimuovi dai preferiti',
    'markVisitedBeforeRating': 'Segna questo luogo come visitato prima di valutarlo.', 'all': 'Tutto', 'allFilters': 'Tutto',
    'minimumRating': 'Valutazione minima', 'clearFilters': 'Cancella filtri', 'exploreTours': 'Esplora i tour',
    'bookingComingSoon': 'La funzione di prenotazione arriverà presto!', 'cancel': 'Annulla', 'profileNotFound': 'Profilo non trovato.',
    'countryCode': 'Codice paese', 'visitDay': 'Giorno della visita', 'operationFailed': 'Operazione non riuscita',
    'deleteShareTitle': 'Eliminare questo post?', 'deleteShareMessage': 'Questo post e tutte le sue immagini verranno eliminati.',
    'share': 'Condividi', 'delete': 'Elimina', 'shareDeleted': 'Post eliminato.',
    'shareDeleteFailed': 'Impossibile eliminare il post: {error}', 'createShare': 'Crea post', 'deleteShare': 'Elimina post', 'viewProfile': 'Vedi profilo',
    'filter': 'Filtra',
    'noToursFound': 'Nessun tour trovato',
    'adjustFilters': 'Prova a modificare i filtri',
    'reset': 'Ripristina',
    'dailyItinerary': 'Itinerario giornaliero',
    'tourDayLabel': 'Giorno {day}',
    'visitsLabel': 'Visite',
    'noShareableVisits': 'Nessuna visita condivisibile al momento.',
    'atLeastOneImage': 'Seleziona almeno un’immagine.',
    'newShare': 'Nuovo post',
    'shareFailed': 'Impossibile creare il post: {error}',
    'reviews': 'recensioni',
    'loadingImage': 'Caricamento immagine…',
    'communityPostHint': 'Aggiungi fino a 5 foto, una descrizione e una posizione.',
    'communityCaptionHint': 'Racconta cosa hai scoperto…',
    'communityLocationHint': 'es. Kayseri, Türkiye',
    'refresh': 'Aggiorna',
    'shareError': 'Condivisione non riuscita: {error}',
  },
  'ar': {
    'community': 'المجتمع', 'showOnMap': 'عرض على الخريطة', 'showCity': 'عرض المدينة', 'openDetails': 'فتح التفاصيل',
    'mapEmpty': 'لم يتم العثور على اكتشافات في هذه المدينة.', 'mapHint': 'اضغط على نقطة في الخريطة لفتح التفاصيل والوصف والصورة.',
    'discoveryCount': '{count} اكتشافات', 'favoriteAdd': 'إضافة إلى المفضلة', 'favoriteRemove': 'إزالة من المفضلة',
    'markVisitedBeforeRating': 'سجّل هذا المكان كمُزار قبل تقييمه.', 'all': 'الكل', 'allFilters': 'الكل', 'minimumRating': 'الحد الأدنى للتقييم',
    'clearFilters': 'مسح الفلاتر', 'exploreTours': 'استكشف الجولات', 'bookingComingSoon': 'ستتوفر ميزة الحجز قريبًا!', 'cancel': 'إلغاء',
    'profileNotFound': 'لم يتم العثور على الملف الشخصي.', 'countryCode': 'رمز الدولة', 'visitDay': 'يوم الزيارة', 'operationFailed': 'فشلت العملية',
    'deleteShareTitle': 'حذف هذا المنشور؟', 'deleteShareMessage': 'سيتم حذف هذا المنشور وجميع صوره.', 'share': 'مشاركة', 'delete': 'حذف',
    'shareDeleted': 'تم حذف المنشور.', 'shareDeleteFailed': 'تعذر حذف المنشور: {error}', 'createShare': 'إنشاء منشور', 'deleteShare': 'حذف المنشور', 'viewProfile': 'عرض الملف الشخصي',
    'filter': 'تصفية',
    'noToursFound': 'لم يتم العثور على جولات',
    'adjustFilters': 'حاول تعديل الفلاتر',
    'reset': 'إعادة تعيين',
    'dailyItinerary': 'البرنامج اليومي',
    'tourDayLabel': 'اليوم {day}',
    'visitsLabel': 'الزيارات',
    'noShareableVisits': 'لا توجد زيارات قابلة للمشاركة بعد.',
    'atLeastOneImage': 'اختر صورة واحدة على الأقل.',
    'newShare': 'منشور جديد',
    'shareFailed': 'تعذر إنشاء المنشور: {error}',
    'reviews': 'مراجعات',
    'loadingImage': 'جارٍ تحميل الصورة…',
    'communityPostHint': 'أضف حتى 5 صور ووصفًا وموقعًا.',
    'communityCaptionHint': 'أخبر الآخرين بما اكتشفته…',
    'communityLocationHint': 'مثال: Kayseri, Türkiye',
    'refresh': 'تحديث',
    'shareError': 'فشلت المشاركة: {error}',
  },
  'zh': {
    'community': '社区', 'showOnMap': '在地图上查看', 'showCity': '查看城市', 'openDetails': '打开详情', 'mapEmpty': '这座城市没有找到探索地点。',
    'mapHint': '点击地图上的地点，查看详情、介绍和图片。', 'discoveryCount': '{count} 个探索地点', 'favoriteAdd': '加入收藏', 'favoriteRemove': '取消收藏',
    'markVisitedBeforeRating': '评分前请先将此地点标记为已访问。', 'all': '全部', 'allFilters': '全部', 'minimumRating': '最低评分', 'clearFilters': '清除筛选',
    'exploreTours': '探索旅行团', 'bookingComingSoon': '预订功能即将推出！', 'cancel': '取消', 'profileNotFound': '未找到个人资料。', 'countryCode': '国家代码',
    'visitDay': '访问日期', 'operationFailed': '操作失败', 'deleteShareTitle': '删除这条帖子？', 'deleteShareMessage': '这条帖子及其中的所有图片都会被删除。',
    'share': '分享', 'delete': '删除', 'shareDeleted': '帖子已删除。', 'shareDeleteFailed': '无法删除帖子：{error}', 'createShare': '创建帖子', 'deleteShare': '删除帖子', 'viewProfile': '查看个人资料',
    'filter': '筛选',
    'noToursFound': '未找到旅行团',
    'adjustFilters': '尝试调整筛选条件',
    'reset': '重置',
    'dailyItinerary': '每日行程',
    'tourDayLabel': '第 {day} 天',
    'visitsLabel': '访问记录',
    'noShareableVisits': '暂无可分享的访问记录。',
    'atLeastOneImage': '请至少选择一张图片。',
    'newShare': '新帖子',
    'shareFailed': '无法创建帖子：{error}',
    'reviews': '条评价',
    'loadingImage': '正在加载图片…',
    'communityPostHint': '最多添加5张图片、描述和位置。',
    'communityCaptionHint': '告诉大家你发现了什么…',
    'communityLocationHint': '例如 Kayseri, Türkiye',
    'refresh': '刷新',
    'shareError': '分享失败：{error}',
  },
  'ru': {
    'community': 'Сообщество', 'showOnMap': 'Показать на карте', 'showCity': 'Показать город', 'openDetails': 'Открыть подробности',
    'mapEmpty': 'В этом городе не найдено мест для открытий.', 'mapHint': 'Нажмите на точку на карте, чтобы открыть подробности, описание и изображение.',
    'discoveryCount': '{count} открытий', 'favoriteAdd': 'Добавить в избранное', 'favoriteRemove': 'Удалить из избранного',
    'markVisitedBeforeRating': 'Перед оценкой отметьте это место как посещённое.', 'all': 'Все', 'allFilters': 'Все', 'minimumRating': 'Минимальная оценка',
    'clearFilters': 'Очистить фильтры', 'exploreTours': 'Исследовать туры', 'bookingComingSoon': 'Бронирование скоро станет доступно!', 'cancel': 'Отмена',
    'profileNotFound': 'Профиль не найден.', 'countryCode': 'Код страны', 'visitDay': 'День посещения', 'operationFailed': 'Операция не выполнена',
    'deleteShareTitle': 'Удалить эту публикацию?', 'deleteShareMessage': 'Эта публикация и все её изображения будут удалены.', 'share': 'Поделиться', 'delete': 'Удалить',
    'shareDeleted': 'Публикация удалена.', 'shareDeleteFailed': 'Не удалось удалить публикацию: {error}', 'createShare': 'Создать публикацию', 'deleteShare': 'Удалить публикацию', 'viewProfile': 'Открыть профиль',
    'filter': 'Фильтр',
    'noToursFound': 'Туры не найдены',
    'adjustFilters': 'Попробуйте изменить фильтры',
    'reset': 'Сбросить',
    'dailyItinerary': 'План на день',
    'tourDayLabel': 'День {day}',
    'visitsLabel': 'Посещения',
    'noShareableVisits': 'Пока нет посещений для публикации.',
    'atLeastOneImage': 'Выберите хотя бы одно изображение.',
    'newShare': 'Новая публикация',
    'shareFailed': 'Не удалось создать публикацию: {error}',
    'reviews': 'отзывов',
    'loadingImage': 'Загрузка изображения…',
    'communityPostHint': 'Добавьте до 5 фотографий, описание и место.',
    'communityCaptionHint': 'Расскажите, что вы открыли…',
    'communityLocationHint': 'например, Kayseri, Türkiye',
    'refresh': 'Обновить',
    'shareError': 'Не удалось поделиться: {error}',
  },
  'ko': {
    'community': '커뮤니티', 'showOnMap': '지도에서 보기', 'showCity': '도시 보기', 'openDetails': '상세 정보 열기', 'mapEmpty': '이 도시에서 발견 장소를 찾을 수 없습니다.',
    'mapHint': '지도에서 지점을 눌러 상세 정보, 설명 및 이미지를 확인하세요.', 'discoveryCount': '발견 {count}개', 'favoriteAdd': '즐겨찾기에 추가', 'favoriteRemove': '즐겨찾기에서 삭제',
    'markVisitedBeforeRating': '평가하기 전에 이 장소를 방문한 것으로 표시하세요.', 'all': '전체', 'allFilters': '전체', 'minimumRating': '최소 평점', 'clearFilters': '필터 지우기',
    'exploreTours': '투어 둘러보기', 'bookingComingSoon': '예약 기능이 곧 제공됩니다!', 'cancel': '취소', 'profileNotFound': '프로필을 찾을 수 없습니다.', 'countryCode': '국가 코드',
    'visitDay': '방문일', 'operationFailed': '작업에 실패했습니다.', 'deleteShareTitle': '이 게시물을 삭제할까요?', 'deleteShareMessage': '이 게시물과 포함된 모든 이미지가 삭제됩니다.',
    'share': '공유', 'delete': '삭제', 'shareDeleted': '게시물이 삭제되었습니다.', 'shareDeleteFailed': '게시물을 삭제할 수 없습니다: {error}', 'createShare': '게시물 만들기', 'deleteShare': '게시물 삭제', 'viewProfile': '프로필 보기',
    'filter': '필터',
    'noToursFound': '투어를 찾을 수 없습니다',
    'adjustFilters': '필터를 조정해 보세요',
    'reset': '초기화',
    'dailyItinerary': '일일 일정',
    'tourDayLabel': '{day}일차',
    'visitsLabel': '방문 기록',
    'noShareableVisits': '아직 공유할 수 있는 방문 기록이 없습니다.',
    'atLeastOneImage': '이미지를 하나 이상 선택하세요.',
    'newShare': '새 게시물',
    'shareFailed': '게시물을 만들 수 없습니다: {error}',
    'reviews': '리뷰',
    'loadingImage': '이미지 불러오는 중…',
    'communityPostHint': '사진 최대 5장, 설명과 위치를 추가할 수 있습니다.',
    'communityCaptionHint': '무엇을 발견했는지 알려주세요…',
    'communityLocationHint': '예: Kayseri, Türkiye',
    'refresh': '새로고침',
    'shareError': '공유에 실패했습니다: {error}',
  },
  'ja': {
    'community': 'コミュニティ', 'showOnMap': '地図で表示', 'showCity': '都市を表示', 'openDetails': '詳細を開く', 'mapEmpty': 'この都市に探索スポットはありません。',
    'mapHint': '地図上のスポットをタップして、詳細・説明・画像を開きます。', 'discoveryCount': '{count} 件のスポット', 'favoriteAdd': 'お気に入りに追加', 'favoriteRemove': 'お気に入りから削除',
    'markVisitedBeforeRating': '評価する前に、この場所を訪問済みにしてください。', 'all': 'すべて', 'allFilters': 'すべて', 'minimumRating': '最低評価', 'clearFilters': 'フィルターをクリア',
    'exploreTours': 'ツアーを探す', 'bookingComingSoon': '予約機能は近日公開予定です！', 'cancel': 'キャンセル', 'profileNotFound': 'プロフィールが見つかりません。', 'countryCode': '国コード',
    'visitDay': '訪問日', 'operationFailed': '操作に失敗しました', 'deleteShareTitle': 'この投稿を削除しますか？', 'deleteShareMessage': 'この投稿とすべての画像が削除されます。',
    'share': '共有', 'delete': '削除', 'shareDeleted': '投稿を削除しました。', 'shareDeleteFailed': '投稿を削除できませんでした：{error}', 'createShare': '投稿を作成', 'deleteShare': '投稿を削除', 'viewProfile': 'プロフィールを見る',
    'filter': '絞り込み',
    'noToursFound': 'ツアーが見つかりません',
    'adjustFilters': 'フィルターを調整してください',
    'reset': 'リセット',
    'dailyItinerary': '1日の旅程',
    'tourDayLabel': '{day}日目',
    'visitsLabel': '訪問記録',
    'noShareableVisits': '共有できる訪問記録はまだありません。',
    'atLeastOneImage': '画像を1枚以上選択してください。',
    'newShare': '新しい投稿',
    'shareFailed': '投稿を作成できませんでした：{error}',
    'reviews': '件のレビュー',
    'loadingImage': '画像を読み込み中…',
    'communityPostHint': '写真を最大5枚、説明、場所を追加できます。',
    'communityCaptionHint': '何を発見したか教えてください…',
    'communityLocationHint': '例：Kayseri, Türkiye',
    'refresh': '更新',
    'shareError': '共有に失敗しました：{error}',
  },
  'pt': {
    'community': 'Comunidade', 'showOnMap': 'Mostrar no mapa', 'showCity': 'Mostrar cidade', 'openDetails': 'Abrir detalhes', 'mapEmpty': 'Nenhuma descoberta encontrada nesta cidade.',
    'mapHint': 'Toque em um ponto no mapa para abrir detalhes, descrição e imagem.', 'discoveryCount': '{count} descobertas', 'favoriteAdd': 'Adicionar aos favoritos', 'favoriteRemove': 'Remover dos favoritos',
    'markVisitedBeforeRating': 'Marque este local como visitado antes de avaliá-lo.', 'all': 'Todos', 'allFilters': 'Todos', 'minimumRating': 'Avaliação mínima', 'clearFilters': 'Limpar filtros',
    'exploreTours': 'Explorar passeios', 'bookingComingSoon': 'A função de reserva estará disponível em breve!', 'cancel': 'Cancelar', 'profileNotFound': 'Perfil não encontrado.', 'countryCode': 'Código do país',
    'visitDay': 'Dia da visita', 'operationFailed': 'A operação falhou', 'deleteShareTitle': 'Excluir esta publicação?', 'deleteShareMessage': 'Esta publicação e todas as suas imagens serão excluídas.',
    'share': 'Compartilhar', 'delete': 'Excluir', 'shareDeleted': 'Publicação excluída.', 'shareDeleteFailed': 'Não foi possível excluir a publicação: {error}', 'createShare': 'Criar publicação', 'deleteShare': 'Excluir publicação', 'viewProfile': 'Ver perfil',
    'filter': 'Filtrar',
    'noToursFound': 'Nenhum passeio encontrado',
    'adjustFilters': 'Tente ajustar os filtros',
    'reset': 'Redefinir',
    'dailyItinerary': 'Itinerário diário',
    'tourDayLabel': 'Dia {day}',
    'visitsLabel': 'Visitas',
    'noShareableVisits': 'Ainda não há visitas compartilháveis.',
    'atLeastOneImage': 'Selecione pelo menos uma imagem.',
    'newShare': 'Nova publicação',
    'shareFailed': 'Não foi possível criar a publicação: {error}',
    'reviews': 'avaliações',
    'loadingImage': 'Carregando imagem…',
    'communityPostHint': 'Adicione até 5 fotos, uma descrição e uma localização.',
    'communityCaptionHint': 'Conte o que você descobriu…',
    'communityLocationHint': 'ex.: Kayseri, Türkiye',
    'refresh': 'Atualizar',
    'shareError': 'Falha ao compartilhar: {error}',
  },
  'nl': {
    'community': 'Community', 'showOnMap': 'Op kaart tonen', 'showCity': 'Stad tonen', 'openDetails': 'Details openen', 'mapEmpty': 'Geen ontdekkingen gevonden in deze stad.',
    'mapHint': 'Tik op een punt op de kaart om details, beschrijving en afbeelding te openen.', 'discoveryCount': '{count} ontdekkingen', 'favoriteAdd': 'Aan favorieten toevoegen', 'favoriteRemove': 'Uit favorieten verwijderen',
    'markVisitedBeforeRating': 'Markeer deze plek als bezocht voordat je hem beoordeelt.', 'all': 'Alles', 'allFilters': 'Alles', 'minimumRating': 'Minimumwaardering', 'clearFilters': 'Filters wissen',
    'exploreTours': 'Tours ontdekken', 'bookingComingSoon': 'De boekingsfunctie komt binnenkort!', 'cancel': 'Annuleren', 'profileNotFound': 'Profiel niet gevonden.', 'countryCode': 'Landcode',
    'visitDay': 'Bezoekdag', 'operationFailed': 'Bewerking mislukt', 'deleteShareTitle': 'Dit bericht verwijderen?', 'deleteShareMessage': 'Dit bericht en alle afbeeldingen worden verwijderd.',
    'share': 'Delen', 'delete': 'Verwijderen', 'shareDeleted': 'Bericht verwijderd.', 'shareDeleteFailed': 'Bericht kon niet worden verwijderd: {error}', 'createShare': 'Bericht maken', 'deleteShare': 'Bericht verwijderen', 'viewProfile': 'Profiel bekijken',
    'filter': 'Filteren',
    'noToursFound': 'Geen tours gevonden',
    'adjustFilters': 'Probeer je filters aan te passen',
    'reset': 'Resetten',
    'dailyItinerary': 'Dagprogramma',
    'tourDayLabel': 'Dag {day}',
    'visitsLabel': 'Bezoeken',
    'noShareableVisits': 'Nog geen deelbare bezoeken.',
    'atLeastOneImage': 'Selecteer minstens één afbeelding.',
    'newShare': 'Nieuw bericht',
    'shareFailed': 'Bericht kon niet worden gemaakt: {error}',
    'reviews': 'reviews',
    'loadingImage': 'Afbeelding laden…',
    'communityPostHint': 'Voeg maximaal 5 foto’s, een beschrijving en een locatie toe.',
    'communityCaptionHint': 'Vertel wat je hebt ontdekt…',
    'communityLocationHint': 'bijv. Kayseri, Türkiye',
    'refresh': 'Vernieuwen',
    'shareError': 'Delen mislukt: {error}',
  },

};
