/// Localization for UI literals found outside the legacy key dictionary.
const hardcodedUiLocalizationOverrides = <String, Map<String, String>>{
  'en': {
    'homeCities': 'Cities',
    'homeCitiesSubtitle': '{cities} cities · {items} discoveries',
    'homeFavorites': 'Your favorites',
    'homeFavoritesSubtitle': 'Quickly return to discoveries you saved.',
    'homeHero': 'Choose what to discover, not just where to go.',
    'homeExploreCities': 'Explore cities',
    'homeExploreCitiesSubtitle': 'Explore cities, then see what is where on the map.',
    'refresh': 'Refresh',
    'communityLoadFailed': 'Could not load posts',
    'communityLoadFailedHint': 'Check your connection and try again.',
    'firstShare': 'Create the first post',
    'firstShareHint': 'Add up to 5 photos, a description and a location.',
    'deletePost': 'Delete post',
    'atLeastOneImage': 'Select at least one image.',
    'newPost': 'New post',
    'communityCaptionHint': 'Tell people what you discovered…',
    'communityLocationHint': 'e.g. Kayseri, Türkiye',
    'useCurrentLocation': 'Use my current location',
    'publishing': 'Publishing…',
    'publishPost': 'Publish post',
    'shareFailed': 'Post could not be created: {error}',
    'shareDeleteFailed': 'Post could not be deleted: {error}',
    'operationFailedWithError': 'Operation failed: {error}',
    'profileNotFound': 'Profile not found.',
    'visits': 'Visits',
    'savedDays': 'Saved days',
    'filterTours': 'Filter tours',
    'destination': 'Destination',
    'duration': 'Duration',
    'travelStyle': 'Travel style',
    'sortBy': 'Sort by',
    'reset': 'Reset',
    'applyFilters': 'Apply filters',
    'days': 'days',
    'highestRated': 'Highest rated',
    'mostPopular': 'Most popular',
    'searchTours': 'Search tours, cities…',
    'bookThisTour': 'Book this tour',
    'travelDays': 'TRAVEL DAYS',
    'countries': 'COUNTRIES',
    'cities': 'CITIES',
    'generatedWithEdible': 'Generated with Edible',
    'myWorldOneBite': 'My world, one bite at a time.',
  },
  'tr': {
    'homeCities': 'Şehirler',
    'homeCitiesSubtitle': '{cities} şehir · {items} keşif noktası',
    'homeFavorites': 'Favorilerin',
    'homeFavoritesSubtitle': 'Kaydettiğin keşiflere hızlıca dön.',
    'homeHero': 'Nereye gideceğini değil, ne keşfedeceğini seç.',
    'homeExploreCities': 'Şehirleri keşfet',
    'homeExploreCitiesSubtitle': 'Şehirleri keşfet, sonra haritada neyin nerede olduğunu gör.',
    'refresh': 'Yenile',
    'communityLoadFailed': 'Paylaşımlar yüklenemedi',
    'communityLoadFailedHint': 'Bağlantını kontrol edip tekrar dene.',
    'firstShare': 'İlk paylaşımı sen yap',
    'firstShareHint': 'En fazla 5 fotoğraf, açıklama ve konum ekleyebilirsin.',
    'deletePost': 'Paylaşımı sil',
    'atLeastOneImage': 'En az 1 görsel seçmelisin.',
    'newPost': 'Yeni paylaşım',
    'communityCaptionHint': 'Nerede ne keşfettiğini anlat…',
    'communityLocationHint': 'Örn. Kayseri, Türkiye',
    'useCurrentLocation': 'Mevcut konumumu ekle',
    'publishing': 'Paylaşılıyor…',
    'publishPost': 'Paylaşımı yayınla',
    'shareFailed': 'Paylaşım oluşturulamadı: {error}',
    'shareDeleteFailed': 'Paylaşım silinemedi: {error}',
    'operationFailedWithError': 'İşlem başarısız: {error}',
    'profileNotFound': 'Profil bulunamadı.',
    'visits': 'Ziyaret',
    'savedDays': 'Kayıtlı gün',
    'filterTours': 'Turları filtrele',
    'destination': 'Destinasyon',
    'duration': 'Süre',
    'travelStyle': 'Seyahat tarzı',
    'sortBy': 'Sıralama',
    'reset': 'Sıfırla',
    'applyFilters': 'Filtreleri uygula',
    'days': 'gün',
    'highestRated': 'En yüksek puanlı',
    'mostPopular': 'En popüler',
    'searchTours': 'Tur veya şehir ara…',
    'bookThisTour': 'Bu turu ayırt',
    'travelDays': 'SEYAHAT GÜNÜ',
    'countries': 'ÜLKELER',
    'cities': 'ŞEHİRLER',
    'generatedWithEdible': 'Edible ile oluşturuldu',
    'myWorldOneBite': 'Benim dünyam, her lokmada bir keşif.',
  },
  'de': {
    'homeCities': 'Städte',
    'homeCitiesSubtitle': '{cities} Städte · {items} Entdeckungen',
    'homeFavorites': 'Deine Favoriten',
    'homeFavoritesSubtitle': 'Kehre schnell zu deinen gespeicherten Entdeckungen zurück.',
    'homeHero': 'Entdecke, was du erleben möchtest – nicht nur, wohin du gehst.',
    'homeExploreCities': 'Städte entdecken',
    'homeExploreCitiesSubtitle': 'Entdecke Städte und sieh anschließend auf der Karte, was wo liegt.',
    'refresh': 'Aktualisieren',
    'communityLoadFailed': 'Beiträge konnten nicht geladen werden',
    'communityLoadFailedHint': 'Überprüfe deine Verbindung und versuche es erneut.',
    'firstShare': 'Ersten Beitrag erstellen',
    'firstShareHint': 'Füge bis zu 5 Fotos, eine Beschreibung und einen Ort hinzu.',
    'deletePost': 'Beitrag löschen',
    'atLeastOneImage': 'Wähle mindestens ein Bild aus.',
    'newPost': 'Neuer Beitrag',
    'communityCaptionHint': 'Erzähle, was du entdeckt hast…',
    'communityLocationHint': 'z. B. Kayseri, Türkei',
    'useCurrentLocation': 'Meinen aktuellen Standort hinzufügen',
    'publishing': 'Wird veröffentlicht…',
    'publishPost': 'Beitrag veröffentlichen',
    'shareFailed': 'Beitrag konnte nicht erstellt werden: {error}',
    'shareDeleteFailed': 'Beitrag konnte nicht gelöscht werden: {error}',
    'operationFailedWithError': 'Vorgang fehlgeschlagen: {error}',
    'profileNotFound': 'Profil nicht gefunden.',
    'visits': 'Besuche',
    'savedDays': 'Gespeicherte Tage',
    'filterTours': 'Touren filtern',
    'destination': 'Reiseziel',
    'duration': 'Dauer',
    'travelStyle': 'Reisestil',
    'sortBy': 'Sortieren nach',
    'reset': 'Zurücksetzen',
    'applyFilters': 'Filter anwenden',
    'days': 'Tage',
    'highestRated': 'Am höchsten bewertet',
    'mostPopular': 'Am beliebtesten',
    'searchTours': 'Touren, Städte suchen…',
    'bookThisTour': 'Diese Tour buchen',
    'travelDays': 'REISETAGE',
    'countries': 'LÄNDER',
    'cities': 'STÄDTE',
    'generatedWithEdible': 'Mit Edible erstellt',
    'myWorldOneBite': 'Meine Welt, ein Bissen nach dem anderen.',
  },
  'fr': {
    'homeCities': 'Villes',
    'homeCitiesSubtitle': '{cities} villes · {items} découvertes',
    'homeFavorites': 'Vos favoris',
    'homeFavoritesSubtitle': 'Retrouvez rapidement vos découvertes enregistrées.',
    'homeHero': 'Choisissez ce que vous voulez découvrir, pas seulement où aller.',
    'homeExploreCities': 'Explorer les villes',
    'homeExploreCitiesSubtitle': 'Explorez les villes, puis voyez sur la carte où se trouvent les découvertes.',
    'refresh': 'Actualiser',
    'communityLoadFailed': 'Impossible de charger les publications',
    'communityLoadFailedHint': 'Vérifiez votre connexion et réessayez.',
    'firstShare': 'Créer la première publication',
    'firstShareHint': 'Ajoutez jusqu’à 5 photos, une description et un lieu.',
    'deletePost': 'Supprimer la publication',
    'atLeastOneImage': 'Sélectionnez au moins une image.',
    'newPost': 'Nouvelle publication',
    'communityCaptionHint': 'Dites-nous ce que vous avez découvert…',
    'communityLocationHint': 'ex. Kayseri, Turquie',
    'useCurrentLocation': 'Ajouter ma position actuelle',
    'publishing': 'Publication…',
    'publishPost': 'Publier',
    'shareFailed': 'Impossible de créer la publication : {error}',
    'shareDeleteFailed': 'Impossible de supprimer la publication : {error}',
    'operationFailedWithError': 'Échec de l’opération : {error}',
    'profileNotFound': 'Profil introuvable.',
    'visits': 'Visites',
    'savedDays': 'Jours enregistrés',
    'filterTours': 'Filtrer les circuits',
    'destination': 'Destination',
    'duration': 'Durée',
    'travelStyle': 'Style de voyage',
    'sortBy': 'Trier par',
    'reset': 'Réinitialiser',
    'applyFilters': 'Appliquer les filtres',
    'days': 'jours',
    'highestRated': 'Mieux notés',
    'mostPopular': 'Plus populaires',
    'searchTours': 'Rechercher des circuits, villes…',
    'bookThisTour': 'Réserver ce circuit',
    'travelDays': 'JOURS DE VOYAGE',
    'countries': 'PAYS',
    'cities': 'VILLES',
    'generatedWithEdible': 'Généré avec Edible',
    'myWorldOneBite': 'Mon monde, une bouchée à la fois.',
  },
  'es': {
    'homeCities': 'Ciudades',
    'homeCitiesSubtitle': '{cities} ciudades · {items} descubrimientos',
    'homeFavorites': 'Tus favoritos',
    'homeFavoritesSubtitle': 'Vuelve rápidamente a los descubrimientos que guardaste.',
    'homeHero': 'Elige qué descubrir, no solo adónde ir.',
    'homeExploreCities': 'Explorar ciudades',
    'homeExploreCitiesSubtitle': 'Explora ciudades y descubre después qué hay dónde en el mapa.',
    'refresh': 'Actualizar',
    'communityLoadFailed': 'No se pudieron cargar las publicaciones',
    'communityLoadFailedHint': 'Comprueba tu conexión e inténtalo de nuevo.',
    'firstShare': 'Crea la primera publicación',
    'firstShareHint': 'Añade hasta 5 fotos, una descripción y una ubicación.',
    'deletePost': 'Eliminar publicación',
    'atLeastOneImage': 'Selecciona al menos una imagen.',
    'newPost': 'Nueva publicación',
    'communityCaptionHint': 'Cuenta qué descubriste…',
    'communityLocationHint': 'p. ej., Kayseri, Turquía',
    'useCurrentLocation': 'Añadir mi ubicación actual',
    'publishing': 'Publicando…',
    'publishPost': 'Publicar',
    'shareFailed': 'No se pudo crear la publicación: {error}',
    'shareDeleteFailed': 'No se pudo eliminar la publicación: {error}',
    'operationFailedWithError': 'La operación falló: {error}',
    'profileNotFound': 'Perfil no encontrado.',
    'visits': 'Visitas',
    'savedDays': 'Días guardados',
    'filterTours': 'Filtrar tours',
    'destination': 'Destino',
    'duration': 'Duración',
    'travelStyle': 'Estilo de viaje',
    'sortBy': 'Ordenar por',
    'reset': 'Restablecer',
    'applyFilters': 'Aplicar filtros',
    'days': 'días',
    'highestRated': 'Mejor valorados',
    'mostPopular': 'Más populares',
    'searchTours': 'Buscar tours, ciudades…',
    'bookThisTour': 'Reservar este tour',
    'travelDays': 'DÍAS DE VIAJE',
    'countries': 'PAÍSES',
    'cities': 'CIUDADES',
    'generatedWithEdible': 'Generado con Edible',
    'myWorldOneBite': 'Mi mundo, un bocado a la vez.',
  },
  'it': {
    'homeCities': 'Città',
    'homeCitiesSubtitle': '{cities} città · {items} scoperte',
    'homeFavorites': 'I tuoi preferiti',
    'homeFavoritesSubtitle': 'Torna rapidamente alle scoperte che hai salvato.',
    'homeHero': 'Scegli cosa scoprire, non solo dove andare.',
    'homeExploreCities': 'Esplora le città',
    'homeExploreCitiesSubtitle': 'Esplora le città, poi scopri sulla mappa cosa si trova e dove.',
    'refresh': 'Aggiorna',
    'communityLoadFailed': 'Impossibile caricare i post',
    'communityLoadFailedHint': 'Controlla la connessione e riprova.',
    'firstShare': 'Crea il primo post',
    'firstShareHint': 'Aggiungi fino a 5 foto, una descrizione e una posizione.',
    'deletePost': 'Elimina post',
    'atLeastOneImage': 'Seleziona almeno un’immagine.',
    'newPost': 'Nuovo post',
    'communityCaptionHint': 'Racconta cosa hai scoperto…',
    'communityLocationHint': 'es. Kayseri, Turchia',
    'useCurrentLocation': 'Aggiungi la mia posizione attuale',
    'publishing': 'Pubblicazione…',
    'publishPost': 'Pubblica',
    'shareFailed': 'Impossibile creare il post: {error}',
    'shareDeleteFailed': 'Impossibile eliminare il post: {error}',
    'operationFailedWithError': 'Operazione non riuscita: {error}',
    'profileNotFound': 'Profilo non trovato.',
    'visits': 'Visite',
    'savedDays': 'Giorni salvati',
    'filterTours': 'Filtra i tour',
    'destination': 'Destinazione',
    'duration': 'Durata',
    'travelStyle': 'Stile di viaggio',
    'sortBy': 'Ordina per',
    'reset': 'Ripristina',
    'applyFilters': 'Applica filtri',
    'days': 'giorni',
    'highestRated': 'Più votati',
    'mostPopular': 'Più popolari',
    'searchTours': 'Cerca tour, città…',
    'bookThisTour': 'Prenota questo tour',
    'travelDays': 'GIORNI DI VIAGGIO',
    'countries': 'PAESI',
    'cities': 'CITTÀ',
    'generatedWithEdible': 'Generato con Edible',
    'myWorldOneBite': 'Il mio mondo, un boccone alla volta.',
  },
  'ar': {
    'homeCities': 'المدن',
    'homeCitiesSubtitle': '{cities} مدن · {items} اكتشافات',
    'homeFavorites': 'مفضلاتك',
    'homeFavoritesSubtitle': 'عد سريعًا إلى الاكتشافات التي حفظتها.',
    'homeHero': 'اختر ما تريد اكتشافه، وليس فقط إلى أين تذهب.',
    'homeExploreCities': 'استكشف المدن',
    'homeExploreCitiesSubtitle': 'استكشف المدن، ثم تعرف على أماكن الاكتشافات على الخريطة.',
    'refresh': 'تحديث',
    'communityLoadFailed': 'تعذر تحميل المنشورات',
    'communityLoadFailedHint': 'تحقق من اتصالك وحاول مرة أخرى.',
    'firstShare': 'أنشئ أول منشور',
    'firstShareHint': 'أضف ما يصل إلى 5 صور ووصفًا وموقعًا.',
    'deletePost': 'حذف المنشور',
    'atLeastOneImage': 'اختر صورة واحدة على الأقل.',
    'newPost': 'منشور جديد',
    'communityCaptionHint': 'أخبر الناس بما اكتشفته…',
    'communityLocationHint': 'مثال: قيصري، تركيا',
    'useCurrentLocation': 'إضافة موقعي الحالي',
    'publishing': 'جارٍ النشر…',
    'publishPost': 'نشر المنشور',
    'shareFailed': 'تعذر إنشاء المنشور: {error}',
    'shareDeleteFailed': 'تعذر حذف المنشور: {error}',
    'operationFailedWithError': 'فشلت العملية: {error}',
    'profileNotFound': 'لم يتم العثور على الملف الشخصي.',
    'visits': 'الزيارات',
    'savedDays': 'الأيام المحفوظة',
    'filterTours': 'تصفية الجولات',
    'destination': 'الوجهة',
    'duration': 'المدة',
    'travelStyle': 'نمط السفر',
    'sortBy': 'ترتيب حسب',
    'reset': 'إعادة ضبط',
    'applyFilters': 'تطبيق الفلاتر',
    'days': 'أيام',
    'highestRated': 'الأعلى تقييمًا',
    'mostPopular': 'الأكثر شعبية',
    'searchTours': 'ابحث عن الجولات والمدن…',
    'bookThisTour': 'احجز هذه الجولة',
    'travelDays': 'أيام السفر',
    'countries': 'الدول',
    'cities': 'المدن',
    'generatedWithEdible': 'تم إنشاؤه باستخدام Edible',
    'myWorldOneBite': 'عالمي، لقمة تلو الأخرى.',
  },
  'zh': {
    'homeCities': '城市',
    'homeCitiesSubtitle': '{cities} 个城市 · {items} 个发现',
    'homeFavorites': '我的收藏',
    'homeFavoritesSubtitle': '快速返回你保存的发现。',
    'homeHero': '选择你想探索的内容，而不只是目的地。',
    'homeExploreCities': '探索城市',
    'homeExploreCitiesSubtitle': '探索城市，然后在地图上查看各个发现的位置。',
    'refresh': '刷新',
    'communityLoadFailed': '无法加载帖子',
    'communityLoadFailedHint': '请检查网络连接后重试。',
    'firstShare': '创建第一篇帖子',
    'firstShareHint': '添加最多 5 张照片、描述和位置。',
    'deletePost': '删除帖子',
    'atLeastOneImage': '至少选择一张图片。',
    'newPost': '新帖子',
    'communityCaptionHint': '告诉大家你发现了什么…',
    'communityLocationHint': '例如：Kayseri, Türkiye',
    'useCurrentLocation': '添加我的当前位置',
    'publishing': '正在发布…',
    'publishPost': '发布帖子',
    'shareFailed': '无法创建帖子：{error}',
    'shareDeleteFailed': '无法删除帖子：{error}',
    'operationFailedWithError': '操作失败：{error}',
    'profileNotFound': '未找到个人资料。',
    'visits': '访问记录',
    'savedDays': '已保存天数',
    'filterTours': '筛选行程',
    'destination': '目的地',
    'duration': '时长',
    'travelStyle': '旅行风格',
    'sortBy': '排序方式',
    'reset': '重置',
    'applyFilters': '应用筛选',
    'days': '天',
    'highestRated': '评分最高',
    'mostPopular': '最受欢迎',
    'searchTours': '搜索行程、城市…',
    'bookThisTour': '预订此行程',
    'travelDays': '旅行天数',
    'countries': '国家',
    'cities': '城市',
    'generatedWithEdible': '由 Edible 生成',
    'myWorldOneBite': '我的世界，一口一口探索。',
  },
  'ru': {
    'homeCities': 'Города',
    'homeCitiesSubtitle': '{cities} городов · {items} открытий',
    'homeFavorites': 'Избранное',
    'homeFavoritesSubtitle': 'Быстро возвращайтесь к сохранённым открытиям.',
    'homeHero': 'Выбирайте, что открыть, а не только куда поехать.',
    'homeExploreCities': 'Исследовать города',
    'homeExploreCitiesSubtitle': 'Исследуйте города, а затем смотрите на карте, где что находится.',
    'refresh': 'Обновить',
    'communityLoadFailed': 'Не удалось загрузить публикации',
    'communityLoadFailedHint': 'Проверьте соединение и повторите попытку.',
    'firstShare': 'Создайте первую публикацию',
    'firstShareHint': 'Добавьте до 5 фото, описание и местоположение.',
    'deletePost': 'Удалить публикацию',
    'atLeastOneImage': 'Выберите хотя бы одно изображение.',
    'newPost': 'Новая публикация',
    'communityCaptionHint': 'Расскажите, что вы открыли…',
    'communityLocationHint': 'например, Kayseri, Türkiye',
    'useCurrentLocation': 'Добавить моё текущее местоположение',
    'publishing': 'Публикация…',
    'publishPost': 'Опубликовать',
    'shareFailed': 'Не удалось создать публикацию: {error}',
    'shareDeleteFailed': 'Не удалось удалить публикацию: {error}',
    'operationFailedWithError': 'Операция не выполнена: {error}',
    'profileNotFound': 'Профиль не найден.',
    'visits': 'Посещения',
    'savedDays': 'Сохранённые дни',
    'filterTours': 'Фильтр туров',
    'destination': 'Направление',
    'duration': 'Продолжительность',
    'travelStyle': 'Стиль путешествия',
    'sortBy': 'Сортировать по',
    'reset': 'Сбросить',
    'applyFilters': 'Применить фильтры',
    'days': 'дн.',
    'highestRated': 'С самым высоким рейтингом',
    'mostPopular': 'Самые популярные',
    'searchTours': 'Поиск туров, городов…',
    'bookThisTour': 'Забронировать тур',
    'travelDays': 'ДНИ ПУТЕШЕСТВИЙ',
    'countries': 'СТРАНЫ',
    'cities': 'ГОРОДА',
    'generatedWithEdible': 'Создано с помощью Edible',
    'myWorldOneBite': 'Мой мир, по одному кусочку за раз.',
  },
  'ko': {
    'homeCities': '도시',
    'homeCitiesSubtitle': '{cities}개 도시 · {items}개 발견',
    'homeFavorites': '즐겨찾기',
    'homeFavoritesSubtitle': '저장한 발견으로 빠르게 돌아가세요.',
    'homeHero': '어디로 갈지만이 아니라 무엇을 발견할지 선택하세요.',
    'homeExploreCities': '도시 탐색',
    'homeExploreCitiesSubtitle': '도시를 탐색한 다음 지도에서 각 발견의 위치를 확인하세요.',
    'refresh': '새로고침',
    'communityLoadFailed': '게시물을 불러오지 못했습니다',
    'communityLoadFailedHint': '연결을 확인하고 다시 시도하세요.',
    'firstShare': '첫 게시물 만들기',
    'firstShareHint': '최대 5장의 사진, 설명 및 위치를 추가하세요.',
    'deletePost': '게시물 삭제',
    'atLeastOneImage': '이미지를 하나 이상 선택하세요.',
    'newPost': '새 게시물',
    'communityCaptionHint': '무엇을 발견했는지 알려주세요…',
    'communityLocationHint': '예: Kayseri, Türkiye',
    'useCurrentLocation': '현재 위치 추가',
    'publishing': '게시 중…',
    'publishPost': '게시물 게시',
    'shareFailed': '게시물을 만들 수 없습니다: {error}',
    'shareDeleteFailed': '게시물을 삭제할 수 없습니다: {error}',
    'operationFailedWithError': '작업에 실패했습니다: {error}',
    'profileNotFound': '프로필을 찾을 수 없습니다.',
    'visits': '방문',
    'savedDays': '저장된 일수',
    'filterTours': '투어 필터',
    'destination': '목적지',
    'duration': '기간',
    'travelStyle': '여행 스타일',
    'sortBy': '정렬 기준',
    'reset': '초기화',
    'applyFilters': '필터 적용',
    'days': '일',
    'highestRated': '평점 높은 순',
    'mostPopular': '인기순',
    'searchTours': '투어, 도시 검색…',
    'bookThisTour': '이 투어 예약',
    'travelDays': '여행 일수',
    'countries': '국가',
    'cities': '도시',
    'generatedWithEdible': 'Edible로 생성됨',
    'myWorldOneBite': '나의 세계, 한입씩.',
  },
  'ja': {
    'homeCities': '都市',
    'homeCitiesSubtitle': '{cities}都市 · {items}件の発見',
    'homeFavorites': 'お気に入り',
    'homeFavoritesSubtitle': '保存した発見にすぐ戻れます。',
    'homeHero': '行き先だけでなく、何を発見するかを選びましょう。',
    'homeExploreCities': '都市を探索',
    'homeExploreCitiesSubtitle': '都市を探索して、地図でそれぞれの発見がどこにあるか確認しましょう。',
    'refresh': '更新',
    'communityLoadFailed': '投稿を読み込めませんでした',
    'communityLoadFailedHint': '接続を確認して、もう一度お試しください。',
    'firstShare': '最初の投稿を作成',
    'firstShareHint': '写真5枚まで、説明、場所を追加できます。',
    'deletePost': '投稿を削除',
    'atLeastOneImage': '画像を1枚以上選択してください。',
    'newPost': '新しい投稿',
    'communityCaptionHint': '何を発見したか教えてください…',
    'communityLocationHint': '例：Kayseri, Türkiye',
    'useCurrentLocation': '現在地を追加',
    'publishing': '公開中…',
    'publishPost': '投稿する',
    'shareFailed': '投稿を作成できませんでした：{error}',
    'shareDeleteFailed': '投稿を削除できませんでした：{error}',
    'operationFailedWithError': '操作に失敗しました：{error}',
    'profileNotFound': 'プロフィールが見つかりません。',
    'visits': '訪問',
    'savedDays': '保存日数',
    'filterTours': 'ツアーを絞り込む',
    'destination': '目的地',
    'duration': '期間',
    'travelStyle': '旅行スタイル',
    'sortBy': '並べ替え',
    'reset': 'リセット',
    'applyFilters': 'フィルターを適用',
    'days': '日',
    'highestRated': '高評価',
    'mostPopular': '人気順',
    'searchTours': 'ツアー、都市を検索…',
    'bookThisTour': 'このツアーを予約',
    'travelDays': '旅行日数',
    'countries': '国',
    'cities': '都市',
    'generatedWithEdible': 'Edibleで作成',
    'myWorldOneBite': '私の世界、一口ずつ。',
  },
  'pt': {
    'homeCities': 'Cidades',
    'homeCitiesSubtitle': '{cities} cidades · {items} descobertas',
    'homeFavorites': 'Seus favoritos',
    'homeFavoritesSubtitle': 'Volte rapidamente às descobertas que você salvou.',
    'homeHero': 'Escolha o que descobrir, não apenas para onde ir.',
    'homeExploreCities': 'Explorar cidades',
    'homeExploreCitiesSubtitle': 'Explore cidades e veja no mapa onde cada descoberta está localizada.',
    'refresh': 'Atualizar',
    'communityLoadFailed': 'Não foi possível carregar as publicações',
    'communityLoadFailedHint': 'Verifique sua conexão e tente novamente.',
    'firstShare': 'Crie a primeira publicação',
    'firstShareHint': 'Adicione até 5 fotos, uma descrição e uma localização.',
    'deletePost': 'Excluir publicação',
    'atLeastOneImage': 'Selecione pelo menos uma imagem.',
    'newPost': 'Nova publicação',
    'communityCaptionHint': 'Conte o que você descobriu…',
    'communityLocationHint': 'ex.: Kayseri, Türkiye',
    'useCurrentLocation': 'Adicionar minha localização atual',
    'publishing': 'Publicando…',
    'publishPost': 'Publicar',
    'shareFailed': 'Não foi possível criar a publicação: {error}',
    'shareDeleteFailed': 'Não foi possível excluir a publicação: {error}',
    'operationFailedWithError': 'A operação falhou: {error}',
    'profileNotFound': 'Perfil não encontrado.',
    'visits': 'Visitas',
    'savedDays': 'Dias salvos',
    'filterTours': 'Filtrar passeios',
    'destination': 'Destino',
    'duration': 'Duração',
    'travelStyle': 'Estilo de viagem',
    'sortBy': 'Ordenar por',
    'reset': 'Redefinir',
    'applyFilters': 'Aplicar filtros',
    'days': 'dias',
    'highestRated': 'Mais bem avaliados',
    'mostPopular': 'Mais populares',
    'searchTours': 'Pesquisar passeios, cidades…',
    'bookThisTour': 'Reservar este passeio',
    'travelDays': 'DIAS DE VIAGEM',
    'countries': 'PAÍSES',
    'cities': 'CIDADES',
    'generatedWithEdible': 'Gerado com Edible',
    'myWorldOneBite': 'Meu mundo, uma mordida de cada vez.',
  },
  'nl': {
    'homeCities': 'Steden',
    'homeCitiesSubtitle': '{cities} steden · {items} ontdekkingen',
    'homeFavorites': 'Je favorieten',
    'homeFavoritesSubtitle': 'Ga snel terug naar ontdekkingen die je hebt opgeslagen.',
    'homeHero': 'Kies wat je wilt ontdekken, niet alleen waar je naartoe gaat.',
    'homeExploreCities': 'Steden ontdekken',
    'homeExploreCitiesSubtitle': 'Ontdek steden en bekijk daarna op de kaart waar alles zich bevindt.',
    'refresh': 'Vernieuwen',
    'communityLoadFailed': 'Berichten konden niet worden geladen',
    'communityLoadFailedHint': 'Controleer je verbinding en probeer het opnieuw.',
    'firstShare': 'Maak het eerste bericht',
    'firstShareHint': 'Voeg maximaal 5 foto’s, een beschrijving en een locatie toe.',
    'deletePost': 'Bericht verwijderen',
    'atLeastOneImage': 'Selecteer minstens één afbeelding.',
    'newPost': 'Nieuw bericht',
    'communityCaptionHint': 'Vertel wat je hebt ontdekt…',
    'communityLocationHint': 'bijv. Kayseri, Türkiye',
    'useCurrentLocation': 'Mijn huidige locatie toevoegen',
    'publishing': 'Wordt geplaatst…',
    'publishPost': 'Bericht plaatsen',
    'shareFailed': 'Bericht kon niet worden gemaakt: {error}',
    'shareDeleteFailed': 'Bericht kon niet worden verwijderd: {error}',
    'operationFailedWithError': 'Bewerking mislukt: {error}',
    'profileNotFound': 'Profiel niet gevonden.',
    'visits': 'Bezoeken',
    'savedDays': 'Opgeslagen dagen',
    'filterTours': 'Tours filteren',
    'destination': 'Bestemming',
    'duration': 'Duur',
    'travelStyle': 'Reisstijl',
    'sortBy': 'Sorteren op',
    'reset': 'Resetten',
    'applyFilters': 'Filters toepassen',
    'days': 'dagen',
    'highestRated': 'Hoogst beoordeeld',
    'mostPopular': 'Meest populair',
    'searchTours': 'Tours, steden zoeken…',
    'bookThisTour': 'Deze tour boeken',
    'travelDays': 'REISDAGEN',
    'countries': 'LANDEN',
    'cities': 'STEDEN',
    'generatedWithEdible': 'Gegenereerd met Edible',
    'myWorldOneBite': 'Mijn wereld, hap voor hap.',
  },
};
